[tool.poetry]
name = "headscale-webui"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "AGPL"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
Flask = "^2.2.2"
cryptography = "^39.0.0"
python-dateutil = "^2.8.2"
pytz = "^2022.7.1"
Flask-Executor = "^1.0.0"
PyYAML = "^6.0"
pyuwsgi = "^2.0.21"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]